steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/decap-next-test/mmp-docker/mmp-docker',
      '.',
      '--build-arg', 'CLIENT_ID=$CLIENT_ID',
      '--build-arg', 'CLIENT_SECRET=$CLIENT_SECRET'
    ]
    secretEnv: ['CLIENT_ID', 'CLIENT_SECRET']

availableSecrets:
  secretManager:
    - versionName: projects/decap-next-test/secrets/CLIENT_ID/versions/2
      env: 'CLIENT_ID'
    - versionName: projects/decap-next-test/secrets/CLIENT_SECRET/versions/2
      env: 'CLIENT_SECRET'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/decap-next-test/mmp-docker/mmp-docker'