backend:
  name: github
  repo: brown-ccv/mmp-next
  branch: cms
  base_url: https://mmp-lamp.research.brown.edu/
  auth_endpoint: api/auth
media_folder: public/images
collections:
  - name: mmp_pages
    label: Pages
    folder: src/content/pages
    create: false
    filter: {field: tags, value: MMP}
    fields:
      - name: title
        label: Page
        widget: text
      - name: body
        label: Page Content
        widget: markdown
      - name: tags
        label: Project Tags
        widget: list
        min: 1
        max: 2
        collapsed: false
        field: { label: Project, name: project, widget: select, options: ["MMP", "LAMP"] }
  - name: lamp_pages
    label: LAMP Pages
    folder: src/content/pages
    create: false
    filter: {field: tags, value: LAMP}
    fields:
      - name: title
        label: Page
        widget: text
      - name: body
        label: Page Content
        widget: markdown
      - name: tags
        label: Project Tags
        widget: list
        min: 1
        max: 2
        collapsed: false
        field: { label: Project, name: project, widget: select, options: ["MMP", "LAMP"] }
  - name: map
    label: Map
    folder: src/content/map
    create: false
    fields:
      - name: title
        label: Map Version
        widget: text
      - name: image
        label: MMP Community Map
        widget: image
      - name: tags
        label: Project Tags
        widget: list
        min: 1
        max: 2
        collapsed: false
        field: { label: Project, name: project, widget: select, options: ["MMP", "LAMP"] }
  - name: people
    label: People
    folder: src/content/people
    create: true
    fields:
      - name: type
        label: Staff Type
        widget: select
        options: [ 'Leadership', 'Advisors', 'Supporting Staff' ]
      - name: name
        label: Name
        widget: string
      - name: title
        label: Title
        widget: string
      - name: avatar
        required: false
        label: Photo
        widget: image
      - name: bio
        label: Biography
        widget: text
      - name: org
        label: Company/University
        widget: string
      - name: address
        required: false
        label: Mailing Address
        widget: text
      - name: phone
        required: false
        label: Phone Number
        widget: string
      - name: email
        required: false
        label: Email
        widget: string
        pattern: [ '.+@.+\..+', 'Email must follow standard guidelines' ]
      - name: startDate
        label: Year Started Contributions
        widget: datetime
        date_format: YYYY
        time_format: false
      - name: endDate
        label: Year Ended Contributions
        widget: datetime
        date_format: YYYY
        time_format: false
      - name: tags
        label: Project Tags
        widget: list
        min: 1
        max: 2
        collapsed: false
        field: { label: Project, name: project, widget: select, options: ["MMP", "LAMP"] }
  - name: pubs
    label: Publications
    folder: src/content/publications
    create: true
    identifier_field: citation
    slug: '{{fields.classification}}-{{fields.pubDate}}_{{fields.author}}'
    fields:
      - name: classification
        label: Classification
        widget: select
        options: [ 'Book', 'Chapter', 'Article', 'Dissertation' ]
      - name: author
        label: Author(s)
        widget: text
      - name: pubDate
        label: Publish Date
        widget: datetime
        date_format: YYYY
        time_format: false
      - name: citation
        label: Citation
        widget: text
      - name: feature
        label: Featured Publication
        widget: boolean
        required: false
      - name: image
        required: false
        label: Image
        widget: image
      - name: url
        required: false
        label: Link to Publication
        widget: string
      - name: pdf
        required: false
        label: PDF
        widget: file
      - name: tags
        label: Project Tags
        widget: list
        min: 1
        max: 2
        collapsed: false
        field: { label: Project, name: project, widget: select, options: ["MMP", "LAMP"] }
  - name: data
    label: Documentation Data
    create: true
    folder: src/content/data
    fields:
      - name: cat
        label: Category
        widget: select
        options: [ 'Study Design', 'Questionnaire', 'Changes to Questionnaire', 'Codebook', 'Appendices' ]
      - name: title
        label: Title
        widget: string
      - name: description
        label: Description
        widget: text
      - name: version
        label: Field Season
        required: false
      - name: codebookType
        label: Codebook Category
        required: false
        widget: select
        options: [ 'MMP Core', 'Community Level Supplementary', 'State Level Supplementary', 'National Level Supplementary', 'MSA Level Supplementary' ]
      - name: archivo
        required: false
        label: Spanish File
        widget: file
      - name: file
        required: false
        label: English File
        widget: file
      - name: tags
        label: Project Tags
        widget: list
        min: 1
        max: 2
        collapsed: false
        field: { label: Project, name: project, widget: select, options: ["MMP", "LAMP"] }
  - name: news
    label: News
    identifier_field: pubDate
    create: true
    folder: src/content/news
    fields:
      - name: pubDate
        label: Date
        widget: datetime
        date_format: MM.DD.YYYY
        time_format: false
      - name: heroImage
        label: Featured Image
        widget: image
      - name: title
        label: Title
        widget: text
      - name: description
        label: Short Description
        widget: text
      - name: body
        label: Post
        widget: markdown
      - name: tags
        label: Project Tags
        widget: list
        min: 1
        max: 2
        collapsed: false
        field: { label: Project, name: project, widget: select, options: ["MMP", "LAMP"] }
  - name: aims
    label: Aims
    folder: src/content/aims
    create: false
    fields:
      - name: title
        label: Aim
        widget: text
      - name: aim-1
        label: aim 1
        widget: markdown
      - name: aim-2
        label: aim 2
        widget: markdown
      - name: aim-3
        label: aim 3
        widget: markdown
      - name: tag
        label: Project Tags
        widget: select
        options: ["MMP", "LAMP"]
      - name: color
        label: Icon Color
        widget: select
        options: ["blue", "primary", "brown"]
      - name: icon
        label: Icon
        widget: select
        options: ["globe", "pencil", "target"]
